### ISSUE TITLE
Remove temp files from ModifiedPaths on deletion

### ISSUE THREAD

**Issue by sanoursa** [Microsoft/VFSForGit#117]
When a new file is created, it has to be added to the ModifiedPaths collection, even if it is currently .gitignore'd (because it could get unignored later and the file system still has to function correctly if that happens). However, if that file is then deleted before it is ever added to the index or committed, then it should be safe to remove it from the ModifiedPaths list.

We should determine the scenarios in which it is safe to remove entries from the ModifiedPaths list to avoid status runtimes from blowing out as a result of temp files written inside the src directory.

**Comment by wilbaker** [comment]
Additionally, ideally recursive folder entries would be removed after the folder has been deleted (when safe).

For example, if a user creates a folder "foo" and deletes it, and then checks out a branch that has a folder named "foo" that folder should be projected by GVFS rather than having its contents written out by git.
