### ISSUE TITLE
Requesting reset of `features/linuxprototype`

### ISSUE THREAD

**Issue by kivikakk** [microsoft/VFSForGit#1196]
I've rebased the `features/linuxprototype` branch to get the latest `master` changes in — would someone be able to reset it to https://github.com/microsoft/VFSForGit/commit/1b39524a3904fd98f8ed411784f832a781267e00?

Cheers!

/cc @derrickstolee @wilbaker @chrisd8088

**Comment by chrisd8088** [comment]
I believe @kivikakk has set things up so that once this is done (remove branch protection on `features/linuxprototype`, reset to 1b39524, and restore branch protection), our other PRs like #1125 and #1189 will apply cleanly again.

@jrbriggs, would you or someone with the right perms be able to tackle this for us?  Thanks very much for the assistance!

**Comment by jrbriggs** [comment]
I've removed branch protection for the time being @chrisd8088 
/cc @kivikakk @wilbaker @derrickstolee

**Comment by chrisd8088** [comment]
OK -- let me try to reset per @kivikakk's intentions.  Thank you!

**Comment by chrisd8088** [comment]
OK, done, I believe, plus I added in the latest commits to master from today, which may help fix the remaining "loose object" CI failures.  Thank you, and please go ahead and re-enable branch protection whenever is convenient!  Much appreciated, @jrbriggs!

**Comment by kivikakk** [comment]
Thanks John, Chris!
