### ISSUE TITLE
Investigate EndpointSecurity as a replacement for kauth

### ISSUE THREAD

**Issue by jrbriggs** [microsoft/VFSForGit#1237]
With Apple's deprecation of the kauth APIs, we need to investigate EndpointSecurity and identify any gaps that would prevent moving the kext functionality.

#### Functionality and Correctness

- What is the overall architecture of EndpointSecurity?  Can the mount process receive callbacks directly, and can we configure the security extension to run in each process? 
- Are there callbacks for all of the events required by VFS4G?
- Do the auth callbacks have a timeout?  If so, we'll need some way to prevent reads from failing due to slow hydration.
- Are the results of the auth callbacks cached?  If so, is the auth cache TTL race condition a problem again?
    - Background:  By default, the kernel caches (for a short time) when I/O is allowed by kauth kexts.  This caused problems for VFS4G because if an application started enumerating a directory while VFS4G was still expanding it the PrjFS kext would not be called for that application and the application would see incomplete results (e.g. a build would complain that file(s) were missing).  The PrjFS kext was not being called because the kernel cached that I/O was allowed for GVFS.Mount, and the other application (running as the same user as GVFS.Mount) piggy-backed off that OK.  The solution was to [set the auth cache's TTL to 0](https://github.com/microsoft/VFSForGit/blob/fd00f1945848f9fbc8529afed146c2112d82275e/ProjFS.Mac/PrjFSKext/VirtualizationRoots.cpp#L521) to disable it.
- How is provider initiated I/O handled?  Will VFS4G receive callbacks for its own disk activity?
- Are file notifications (the equivalent to file op events) blocking?  If not, are they at least well ordered?

#### Performance

- Every mount process will presumably get notifications for all events in all directories.  Is there some way to restrict the cone of directories that VFS4G is interested in?
- How expensive is the kernel <-> user transition for every notification?  Is there anything we can do to reduce the number of notifications VFS4G will receive?

#### Longer term items to investigate

- Without a kext how will we prevent users from interacting with their repos in a way they shouldn't when VFS4G is not mounted?

**Comment by mjcheetham** [comment]
`<nit>`

Is this "[DriverKit](https://developer.apple.com/documentation/driverkit)" or rather "[System Extensions](https://developer.apple.com/system-extensions/)"?

Specifically "[EndpointSecurity](https://developer.apple.com/documentation/endpointsecurity)" was called out as the replacement for kauth kexts in [this WWDC session](https://developer.apple.com/videos/play/wwdc2019/702/) at 3:15, with DriverKit being the replacement for IOKit-based kexts (and Network Extensions a replacement for networking kexts).

`</nit>`

**Comment by wilbaker** [comment]
### Areas to Investigate

#### Functionality and Correctness

- Are there callbacks for all of the events required by VFS4G?
- Do the auth callbacks have a timeout?  If so, we'll need some way to prevent reads from failing due to slow hydration.
- Are the results of the auth callbacks cached?  If so, is the auth cache TTL race condition a problem again?
    - Background:  By default, the kernel caches (for a short time) when I/O is allowed by kauth kexts.  This caused problems for VFS4G because if an application started enumerating a directory while VFS4G was still expanding it the PrjFS kext would not be called for that application and the application would see incomplete results (e.g. a build would complain that file(s) were missing).  The PrjFS kext was not being called because the kernel cached that I/O was allowed for GVFS.Mount, and the other application (running as the same user as GVFS.Mount) piggy-backed off that OK.  The solution was to [set the auth cache's TTL to 0](https://github.com/microsoft/VFSForGit/blob/fd00f1945848f9fbc8529afed146c2112d82275e/ProjFS.Mac/PrjFSKext/VirtualizationRoots.cpp#L521) to disable it.
- How is provider initiated I/O handled?  Will VFS4G receive callbacks for its own disk activity?
- Are file notifications (the equivalent to file op events) blocking?  If not, are they at least well ordered?

#### Performance

- Every mount process will presumably get notifications for all events in all directories.  Is there some way to restrict the cone of directories that VFS4G is interested in?
- How expensive is the kernel <-> user transition for every notification?  Is there anything we can do to reduce the number of notifications VFS4G will receive?

#### Longer term items to investigate

- Without a kext how will we prevent users from interacting with their repos in a way they shouldn't when VFS4G is not mounted.

**Comment by wilbaker** [comment]
See also 1551306 in Azure DevOps

**Comment by pmj** [comment]
It seems the beta API docs etc. are all publicly available (no login necessary) so I guess there's no NDA on any of this.

As discussed out-of-band today, I'm going to attempt to build a quick & dirty mirrorprovider-like prototype using this API to sound out its limitations and performance characteristics.

**Comment by wilbaker** [comment]
Closing this issue out as the initial spike is completed and radars have been filed for issues uncovered during the investigation.
