### ISSUE TITLE
GVFS Sparse - Extra folders outside of sparse list showing up

### ISSUE THREAD

**Issue by judemars** [microsoft/VFSForGit#1461]
After successfully running "gvfs sparse -a folder1" and "gvfs sparse -l" shows folder1, I have a bunch of other folders still in my repo. 

Response from @kewillford:

I’m guessing that you were using a previous repo and not a new clone and that there were modified files in the paths that continue to show up.  Right now there is not a way to clean up the modified files and the paths that have been affected until we have the dehydration of folders feature.  After we have that feature we can add an automatic cleanup after running a sparse command but this would also affect #2 because we would be removing all those files and would need to know they are not modified before that.

But my question is - git status was clean which means there were no uncommitted modified files - what exactly do you mean by "modified files?" - files in this repo that have ever been modified?

**Comment by kewillford** [comment]
>git status was clean which means there were no uncommitted modified files - what exactly do you mean by "modified files?" - files in this repo that have ever been modified?

Yes, because when you modify a files it is added to the ModifiedPaths.dat of VFSForGit and from that time on git is in control of keeping that file up to date and VFSForGit is out of the way and currently that list is additive only. PR  #1323 will change that with dehydrating folders and removing entries from the ModifiedPaths.dat.  Once that PR in merged we can look at using that feature here to clean up things outside the sparse list.

**Comment by judemars** [comment]
Sounds great - thanks! Will circle back to this when I get back from oof later this month.
