### ISSUE TITLE
CRLF conversions not supported when running under GVFS

### ISSUE THREAD

**Issue by poklau** [microsoft/VFSForGit#1528]
Any plan to allow automatically normalize line endings?

**Comment by jrbriggs** [comment]
No, unfortunately. To correctly project sizes, the size of files on disk must exactly match the size of the blobs. We can't have autocrlf come through and make the file on disk be larger than what was reported to the OS during enumeration because that risks corruption when a program asks for the size of the file, allocates that much memory and reads it all in. If it's CRLF filtered then, it is subject to some amount of truncation.

This is pretty baked into the design of the software and the protocol, so I don't anticipate this changes.

**Comment by Tridy** [comment]
@jrbriggs Could you explain the problem a bit with the mismatch of the file blobs size when using LF vs CRLF, please? 

Lets, I have a repository that works under Git properly. When I try to `gvfs clone`, I get the mentioned: "CRLF conversion is not supported." So, this means that I have LF that should be converted to CRLF? Am I right?

If I want to make it work and in gvfs, do I have an option to convert all lines that uses LF to CRLF from Git and then it will work in gvfs, like [here](https://stackoverflow.com/a/1511273/1694087)?

Are there any other options for making it work? 

Thanks!
