### ISSUE TITLE
gvfs fails with Error: Could not find git.exe.  Ensure that Git is installed.

### ISSUE THREAD

**Issue by Dyoung0606** [microsoft/VFSForGit#1634]
Running gvfs clone fails with "Could not find git.exe. Ensure that Git is installed".

Reproduction steps:

1. Install git 2.25
1. Install gvfs using SetupGVFS.1.0.19224.1.exe
1. Open a **new** Windows Command prompt (to ensure the latest changes to PATH, etc are configured)

```batch
C:\Temp> git --version
git version 2.25.0.windows.1

C:\Temp> gvfs clone https://whatever.com/repo_url
Cannot clone @ C:\TEMP\repo_url
Error: Could not find git.exe.  Ensure that Git is installed.
```

git is installed and in the PATH so gvfs should be able to find it and run without incident.

This is not specific to "clone", the same error appears for any gvfs command

**Comment by jlkweb12** [comment]
Any update on this one? I am also having the same issue.

**Comment by kewillford** [comment]
The git version needs to be the gvfs version that matches the gvfs build.  So it will be something like `git version 2.25.0.vfs.1`.    Both the SetupGVFS and the git installer that need to be installed are assets on the Release here https://github.com/microsoft/VFSForGit/releases.

This error also indicates that git did not install properly for some reason because we are using the install path that is in the registry to check if git is installed.

**Comment by jlkweb12** [comment]
> The git version needs to be the gvfs version that matches the gvfs build. So it will be something like `git version 2.25.0.vfs.1`. Both the SetupGVFS and the git installer that need to be installed are assets on the Release here https://github.com/microsoft/VFSForGit/releases.
> 
> This error also indicates that git did not install properly for some reason because we are using the install path that is in the registry to check if git is installed.

That did it. Thanks

**Comment by kkazala** [comment]
I'm having the same issue
I have correct git version installed: 

```
$ git --version
git version 2.29.0.vfs.0.0

$ gvfs version
GVFS 1.0.20296.6
```
Any ideas?

**Comment by derrickstolee** [comment]
To diagnose, consider:

1. Restarting your command/terminal window. That might reset your `PATH` to match what is expected.
2. Run `where git` to find the resolved version of Git.
3. Reinstall that version of Git. (Use "Add or Remove Programs" to uninstall it first".)
4. Restart your machine.

**Comment by kkazala** [comment]
hi @derrickstolee 

Thank you for your reply :)

I gave it another try, reinstalled git ang gvfs and installed it from the scratch but the result is the same.
After uninstalling git I ran `where git` to ensure there's no git installed. 
After installing it again the `where git` shows C:\Users\_username_\AppData\Local\Programs\Git\cmd\git.exe
I noticed that gvfs is "using the install path that is in the registry to check if git is installed." , so I checked registry and in the `Computer\HKEY_CURRENT_USER\SOFTWARE\GitForWindows `I see LibexecPath=C:\Users\_username_\AppData\Local\Programs\Git\mingw64\libexec\git-core which is correct. 

but neverthless, `gvfs` gives me Error: Could not find git.exe.  Ensure that Git is installed.

How can I troubleshoot it?

**Comment by derrickstolee** [comment]
Thanks for comin gback, @kkazala.

> After installing it again the `where git` shows C:\Users\_username_\AppData\Local\Programs\Git\cmd\git.exe

This seems wrong to me. The preferred installation location is `C:\Program Files\Git\`. Perhaps that is causing the problem because of user/elevation changing the default paths here.

Also, it seems you are running this from CMD. Could you try running from Git Bash instead?

Perhaps this path issue is something that @dscho knows about, especially about some installation wizard choices, such as:
![image](https://user-images.githubusercontent.com/570044/101525162-e95ca400-3958-11eb-8099-a9f7a84739ca.png)

...and...

![image](https://user-images.githubusercontent.com/570044/101525194-f7122980-3958-11eb-94d8-d67905c5bda9.png)

**Comment by dscho** [comment]
I did see occasional reports of Git for Windows being installed on a per-user basis. I am still a bit unclear how that is possible in the first place, in any case, this is not the intended way to install Git for Windows. Instead, it is supposed to be installed via elevated installer into `C:\Program Files\Git`.

**Comment by Dyoung0606** [comment]
On my machine, git is installed in the user folder (instead of the programs folder). As @dscho pointed out, this is because I did an install, but not "elevated".
I'm too lazy to uninstall/reinstall unless that truly is the root of this problem... 😁

**Comment by ReCursia** [comment]
Any updated? I have the same problem

**Comment by derrickstolee** [comment]
The root cause here is if you install Git for Windows only for one user instead of the entire system.

To fix, uninstall Git then re-install for the whole system.

**Comment by ReCursia** [comment]
Solved the problem installing Scalar+Git with InstallScalar.bat, run as administrator
