### ISSUE TITLE
Not able to remove or clone a new repo due to below issue 

### ISSUE THREAD

**Issue by onkarnigam14** [microsoft/VFSForGit#1662]
$ gvfs clone http://msptfsapp01:8080/tfs/UDP/UDP_Main
Clone parameters:
  Repo URL:     http://msptfsapp01:8080/tfs/UDP/UDP_Main
  Cache Server: Default
  Destination:  C:\Users\Manoj.Chakole\git2\UDP_Main
Authenticating...Succeeded
Querying remote for config...Failed
Unable to query /gvfs/config

Manoj.Chakole@Arcvdi-15 MINGW64 ~/git2 (master)
$ gvfs clone http://msptfsapp01:8080/tfs/UDP/UDP_Main
Error: You can't clone inside an existing GVFS repo (C:\Users\Manoj.Chakole\git2\UDP_Main)

Manoj.Chakole@Arcvdi-15 MINGW64 ~/git2 (master)
$

**Comment by derrickstolee** [comment]
Your first clone failed, but it had left the "UDP_Main" directory in-place. We leave that there so we can look at logs to see why the clone failed.

The gvfs/config endpoint is probably disabled because you do not have a `.gitattributes` file at root containing [a line like this](https://github.com/microsoft/VFSForGit/blob/e6a8278d9dfc9b0753d9716885f4cb7d2f7caac4/.gitattributes#L4).

You need to delete that before you try again.
