### ISSUE TITLE
Checkout of single filename triggers index re-parse

### ISSUE THREAD

**Issue by kyle-rader** [Microsoft/VFSForGit#274]
https://github.com/Microsoft/VFSForGit/blob/06793f215847ad3023977380d0623cbf59b6cde1/GVFS/GVFS.Common/GitCommandLineParser.cs#L71

In a large repo (like Office) if I have roughly 2/3 of my repo modified (123MB modifiedPaths file) checking out a single filename takes roughly 3-4 minutes. It looks like the checks could be improved here to see whether or not an index parse is actually needed.

The checkout command I was using when I experienced this was
```
git checkout .\relative\path\filename
```

There is already a note in this function:
```
// Note: we have definitely missed some cases of file paths, e.g.:
//    git checkout branchName fileName (detecting this reliably requires more complicated parsing)
//    git checkout --patch (we currently have no need to optimize this scenario)
```

**Comment by sanoursa** [comment]
This is pretty much "by design". We have to parse the index whenever it gets updated, since the index is the source of truth for what files should be projected. We have made some special case exceptions to this rule, for cases where we can determine from the syntax of the command that it's safe to ignore the update to the index. But it's not possible to determine all such cases from syntax alone - e.g. does "git checkout <symbol>" mean you're checking out a branch or a file? Impossible to know without doing some IO, and also difficult to ensure that we will reproduce the exact same behavior as git in all cases.

I'd be open to identifying more special cases that are identifiable using simple syntax parsing, but I don't think we would take on a general fix any time soon.
