### ISSUE TITLE
Diagnose logs incorrect cache server url

### ISSUE THREAD

**Issue by jrbriggs** [Microsoft/VFSForGit#289]
**Steps to reproduce:**
1. Have a cache server.
2. Run gvfs diagnose.
3. Look in diagnostics.log

**Expected Behavior:**
1. Should have correct cache server url.

Instead shows invalid://repoUrl.

**Comment by derrickstolee** [comment]
This also affects jobs like `gvfs repair` and can even lead to the URL being passed to a credential manager.

**Comment by jeschu1** [comment]
There are 2 different bugs here

1.  Under certain conditions we don't correctly init the enlistment on repair, causing us to use an invalid url.  This is do to a miss on refactoring.
2. If we don't have a cache server we are showing an invalid url instead of nothing.  This is due to us using the default url since it wasn't overwritten on the config lookup.

I will addresss each in separate PRs.
