### ISSUE TITLE
Mac: Create log file for kext logging

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#396]
Kext logging of warnings\error should be recorded to a log file that `gvfs diagnose` can collect.

See #395 for related user-mode issue

**Comment by pmj** [comment]
I'm not sufficiently familiar with the `gvfs diagnose` end, but if you need anything done on the kext/native userlib end for this, let me know.

Do we want to include kext profiling support into this as well in some form? (Certain builds only of course.)

**Comment by pmj** [comment]
My take-away from our out-of-band discussion earlier:

 * As a first deliverable for this, extend/replace `prjfs-log` to be/with a proper daemon that is installed by the installer and runs all the time by default.
 * Add log level filtering in the kext to minimise overhead.
 * By default, log only error-level errors.
 * Allow end-users to temporarily enable more verbose logging.

Things that were discussed elsewhere:

 * Start by logging to macOS's syslog database, and see how we go with that. (+ write some scripts for gathering the logs up from syslog)

**Comment by jrbriggs** [comment]
@pmj That all sounds good to me. Is there any value to log warning-level errors as well by default? Where will `prjfs-log` log to by default?

/cc @wilbaker

**Comment by pmj** [comment]
I've been reading up on the details of macOS's Unified Logging system a bit before I start implementing the log daemon based on it. It seems pretty reasonable to me in general; interestingly, it has an "info" log level that by default doesn't hit disk unless sometime later an error is also logged. So rather than logging everything all the time, it effectively retroactively enables verbose logging if an error occurs. Is that something we'd be interested in using?

The only downside I can see to the whole thing is that there's no programmatic API for querying the log database, only the `log` CLI tool. This tool at least is fairly powerful and also supports a metadata-preserving (i.e. searchable, filterable, etc.) export/archival file format that e.g. Console.app supports reading; so that's something that users could send back to us.

Documentation I've been using:

* [WWDC presentation on (then) new logging system](https://developer.apple.com/videos/play/wwdc2016/721/)
* [Reference documentation](https://developer.apple.com/documentation/os/logging?language=occ)

Given the extremely low barrier to entry (I expect we'll simply be calling [os_log_with_type()](https://developer.apple.com/documentation/os/os_log_with_type?language=objc) instead of printf()ing to stdout in our code.) I suggest the following:

 * Create a variant of prjfs-log that works as a daemon
 * This daemon writes to the unified logging system.
 * Put together some scripts that use the `log` CLI to produce log archives with relevant data for us.
 * See if we like the UX of working with these log archives and associated tooling and then decide if we want to move to something else.

**Comment by wilbaker** [comment]
>It seems pretty reasonable to me in general; interestingly, it has an "info" log level that by default doesn't hit disk unless sometime later an error is also logged. So rather than logging everything all the time, it effectively retroactively enables verbose logging if an error occurs. Is that something we'd be interested in using?

That sounds like a pretty cool feature, I think it's worth giving it a try.

> The only downside I can see to the whole thing is that there's no programmatic API for querying the log database, only the log CLI tool. This tool at least is fairly powerful and also supports a metadata-preserving (i.e. searchable, filterable, etc.) export/archival file format that e.g. Console.app supports reading; so that's something that users could send back to us.

I think the log tool will be enough for VFS4G.  We can update the `gvfs diagnose` verb to call the log CLI tool and then include the resulting export file in the zip file `gvfs diagnose` produces.

> I suggest the following:

The approach you've outlined sounds good to me.

/ cc:@jrbriggs

**Comment by wilbaker** [comment]
@pmj do you have any more code changes planned for this work item?

If we do decide to add "Allow end-users to temporarily enable more verbose logging" we could always move that into a new work item or do it as part of #563 

/cc: @jrbriggs

**Comment by wilbaker** [comment]
> I don't think there's really anything that needs to be done in that regard.

@pmj, @jrbriggs I'm thinking this work item can be closed then?  Any objections?

**Comment by jrbriggs** [comment]
@wilbaker I agree, I'm closing this out. Thank @pmj !
