### ISSUE TITLE
Warn that an enlistment is not using shared object cache

### ISSUE THREAD

**Issue by derrickstolee** [Microsoft/VFSForGit#400]
For almost a year, new enlistments use a shared object cache (per volume) to prevent duplicate data taking up space. However, we never upgraded users from the old per-enlistment object cache model.

We want users to update their enlistments, so add a warning that helps them know to upgrade. This could be a similar warning to the upgrade recommendation.

**Comment by sanoursa** [comment]
@derrickstolee @jrbriggs it's perfectly valid to have a per-repo cache. We allow you to do that even on a branch new clone by passing a unique cache location to the `gvfs clone` command. So I don't think it's as simple as just warning the user if they are not using a shared cache location.

We can perhaps detect the specific data shape left by old repos that were upgraded and kept a unique cache location. But I think we should think about actually doing the data-shape-upgrade ourselves rather than warn the user, because their only recourse is to just reclone.

**Comment by derrickstolee** [comment]
Since this is a valid place to be relative to our product, then maybe this is something to communicate via the individual customers’ ES tools. @jrbriggs what do you think?

**Comment by wilbaker** [comment]
> We can perhaps detect the specific data shape left by old repos that were upgraded and kept a unique cache location. But I think we should think about actually doing the data-shape-upgrade ourselves rather than warn the user, because their only recourse is to just reclone.

One option for this would be the following approach:

1. If we can find a shared cache for the same repo ID, and we're not running unattended, update the old repo to use it (but don't copy over any downloaded objects\pack in the old repo to the shared cache).  We could optionally delete objects\packs we know to be downloaded from the old repo.

2. If we can't find a shared cache for the same repo ID, and we're not unattended, and the old repo stores the downloaded objects in the .gvfs folder, move the objects to the shared object cache and update the repo's configuration.

3. If we can't find a shared cache for the same repo ID, and we're not unattended, and the old repo stored the downloaded objects in the .git folder then it's messier.  We could move over the prefetch packs, but the loose objects would need to stay where they are.

The current auto-heal\configuration code is already quite complex, and so although we could support these upgrades the changes might be non-trivial.

**Comment by sanoursa** [comment]
All of that sounds good, as long as we can differentiate between old repos that need upgrading and new repos that were intentionally set up to not use the shared cache. If the user explicitly asked for a unique cache location, we need to honor that.

**Comment by wilbaker** [comment]
> All of that sounds good, as long as we can differentiate between old repos that need upgrading and new repos that were intentionally set up to not use the shared cache. If the user explicitly asked for a unique cache location, we need to honor that.

Yep I agree, based on the comment here:

```
// Note: Repos cloned with a version of GVFS that predates the local cache will not have a local cache configured
if (!string.IsNullOrWhiteSpace(enlistment.LocalCacheRoot))
{
    this.EnsureLocalCacheIsHealthy(tracer, enlistment, retryConfig, serverGVFSConfig, cacheServer);
}
```

It looks like we could probably use the presence\absence `LocalCacheRoot` to determine if the user specified a specific location for the cache (the idea was that new clones *always* used a shared cache, we just allow users to specify where that local cache should live).  It's been a while since I've really dug into that code though and we'd need to make sure we properly account for all the scenarios.  

If we do decide support this upgrade we might want to leave a breadcrumb around as part of the upgrade in case we ever need to differentiate between these scenarios again.

Something that just crossed my mind that would also need to be sorted out is if\how we do anything with the BlobSizes database.  Things could get messy if we migrate only part of what's stored in the shared cache.

**Comment by jrbriggs** [comment]
@sanoursa I feel like we can mitigate most of the need to write the upgrade step by phrasing a caveat in the warning: 

```
WARNING: This enlistment is not using a shared object cache.
Unless this is intentional (i.e., you cloned using --local-cache-path), consider starting
a new enlistment to get the performance benefits of sharing this cache among all enlistments.
```

Showing something like that at mount time and gvfs status seems like we get most of the benefits for none of the complexity. Thoughts?

/cc @wilbaker @derrickstolee

**Comment by wilbaker** [comment]
> Showing something like that at mount time and gvfs status seems like we get most of the benefits for none of the complexity. Thoughts?

I think the message sounds good, but the tricky part might be figuring out a good time to show it. I would guess most users rely on auto-mount and don't frequently run `gvfs status`.

**Comment by derrickstolee** [comment]
The other thing to worry about is how do we _stop_ sending the message for users who **do** want a non-shared object cache.
