### ISSUE TITLE
GVFS is *not* compatible with git 2.19.1

### ISSUE THREAD

**Issue by OsirisTerje** [Microsoft/VFSForGit#407]
From latest release notes:
"Performance Improvements

Upgraded to Git 2.19. This version brings with it improvements to unpack_trees to speed up checkout, merge, reset, and rebase."

But what happens is:
![image](https://user-images.githubusercontent.com/203432/47207166-d2c6ed80-d38a-11e8-98e8-867955dd08c6.png)

2.19.1 is a non-breaking change to the 2.19.  The GVFS should not be blocked by non-breaking updates of git.

**Comment by sanoursa** [comment]
You can only use VFS for Git with a VFS-enabled version of Git (yours is the standard Git for Windows release). Furthermore, each release of VFS for Git only works with one specific version of Git, because there are often breaking changes across Git versions (breaking with respect to a virtual file system, not with respect to Git behavior).

To use the latest VFS for Git release, you must also install the Git version that was bundled up in the release: https://github.com/Microsoft/VFSForGit/releases/tag/v1.0.18289.1
