### ISSUE TITLE
Uninstalling VFS For Git doesn't clean up filter driver

### ISSUE THREAD

**Issue by kyle-rader** [Microsoft/VFSForGit#423]
Running the VFS For Git uninstaller doesn't cleanup the projfs filter driver and screws up the following VFS For Git installation.

We've hit this issue while trying to upgrade several Azure agent pool machines.

**Comment by kyle-rader** [comment]
TY @wilbaker for helping diagnose this.

**Comment by sanoursa** [comment]
@kyle-rader This is by design. VFS for Git doesn't own the ProjFS driver, and in fact on newer Windows releases it doesn't even install the driver. On older Windows builds we had to install the driver, but we can't uninstall it because other applications can and do take dependencies on it.

How exactly did the uninstall cause an error on the next installation? It sounds like you're on an older Windows release, and if you can guarantee that the driver is not needed on those machines, your best bet may be to uninstall the driver from your own script.

**Comment by jrbriggs** [comment]
We're still hitting this relatively frequently. In an effort to reduce customer frustration, let's check if the version of prjflt.sys matches the version we ship. If so we can copy ProjectedFSLib.dll to the right spot. That should be a low-risk way to mitigating these failures to mount.

**Comment by ChrisGuzak** [comment]
I had this problem on current windows clients. I'm not sure how I got into this state, I had upgrade from previous internal wnidows builds so maybe an upgrade bug. 

It seems the VFS installer should verify that the projected file system optional feature is installed and produce a warning if it is not.
