### ISSUE TITLE
Mac: Looking at a repo's folders in Finder adds the folders to ModifedPaths.dat

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#516]
See related #514

1. `gvfs clone' repo
2. Open Finder in column view
3. Click on the `src` folder (so that its columns are displayed in Finder)

Observe:
- Folders that are selected in Finder are added to ModifedPaths.dat
- With extra logging in the user-mode lib it appears that VFS4G is receiving a PreDelete notification for the root (from the `Finder` process)

This was on macOS High Sierra 10.13.6

**Comment by wilbaker** [comment]
Rather that assuming that all DELETE vnode operations will be deletes, VFS4G might need to track "potential deletes" and only add them to the ModifiedPaths.dat file when we have confirmation the directory has been deleted.

**Comment by wilbaker** [comment]
Fixing #524 should resolve this issue as well.

**Comment by pmj** [comment]
Could this be something to do with the the `KAUTH_VNODE_ACCESS` flag? The Finder is probably just be checking permissions rather than attempting a rmdir, so the flag is probably set. We're currently not checking that, and as we're disabling the auth cache, it should in theory be safe to ignore events with that flag for the purposes of messaging. (not so for returning the correct ALLOW/DENY response of course)

**Comment by wilbaker** [comment]
Fixed by changes in #602
