### ISSUE TITLE
VFSForGit and access control?

### ISSUE THREAD

**Issue by jcoiner** [Microsoft/VFSForGit#556]
It would be nice if there was a way to limit access, such that certain users could be securely excluded from reading certain parts of the tree in a VFSForGit setup. Has anyone thought about whether and how this could work?

I'm an engineer with AMD. AMD could benefit from a monorepo. Our data is fragmented among many repos, mostly Perforce. The fragmentation makes integration difficult, and we're at the limits of Perforce scaling.

One obstacle to moving AMD to VFSForGit is lack of access control support in git and VFSForGit. AMD has lots of data whose distribution should be limited. Sometimes it's a legal requirement -- processor core designs are covered by US export control laws, so AMD cannot allow my thousands of Chinese colleagues to have read access. Sometimes it's a contractual obligation, as when a manufacturing partner shares confidential data with us, and we agree to disclose it only to individuals with a need to know.

So any hypothetical AMD monorepo must support access control.

There are actually two dimensions:
 - We must deny read access of secured data to people without required privileges.
 - We must not leave copies of certain data at rest on disk in certain geographies. (We would still want users in those geographies to have access to the majority of the data in the monorepo which has no such geographic restriction.)

We're on Linux, if that matters. I'm assuming a future in which the Linux VFSForGit port is done.

Has anyone looked at this?

And maybe this is more of a git question than a VFSForGit question. Maybe the VFS layer is part of the solution, or maybe it can be solved in git and VFSForGit inherits the feature. TBD.

Thanks!

John

**Comment by sanoursa** [comment]
Yes this question has come up quite often, but it is not within the scope of VFSForGit.

The thing to remember is that the fundamental purpose of VFSForGit is to solve a performance and scale problem. It does its very best to behave exactly like git does. Therefore all new features need to go into git itself, before they can be taken advantage of in VFSForGit.

I get your question though. It's very tempting to want VFSForGit to solve the ACL problem, since it is controlling the file system after all, and that's why it comes up with nearly every team who adopts it. However, VFSForGit is not actually in a position to solve the problem. Yes, it can prevent a user from opening a file. But it can't prevent the same user from talking to the server to get that same file, because git itself, and by extension all git services, do not support any intra-repo ACLs.

So the first place to start would be git itself. And, at least in its current form, this is not something that git could support very easily, since the very first thing you do when cloning is download all of the repo's contents.

**Comment by barnabyrobson** [comment]
Hello @jcoiner I'm interested to hear you are at the limits of perforce scaling; what does that limit look like ? I have read, for example, that Nvidia has 8000 users performing 88 million transactions a day. Are you guys way over that ?

**Comment by jcoiner** [comment]
AMD's largest P4 repos are smaller than NVidia's monorepo, probably by ~10x.

Our p4 repos are large enough that we have draconian rules about who is allowed to create a branch, and how many branches may exist.

The basic problem is: if you have a million files in your codeline, and you create a branch, this creates a million pieces of metadata in the p4 depot. Whereas on git, it only creates one piece of metadata. (Subversion also got this right; you have to go back to CVS to find a popular open source version control that got this wrong.) As the branch and its parent evolve, the cost to represent the branch in the git repo grows, and yet it remains a far sparser representation than p4's representation by orders of magnitude. The cost of a branch on git is too cheap to meter, even in a monorepo, IIUC.

Our p4 repos are large enough that we have draconian rules about how long they may exist for. If you create a client and don't touch it for a couple of weeks, it gets wiped off the server. This is because of a bug in p4 (which they would call a feature, but it's clearly a bug) where a lot of metadata about your client -- including the full list of files you have synced -- is stored not on your disk but on the server. So our server admins garbage collect inactive clients to save space on the server. Git, Subversion, and CVS don't have this problem: pulling a working copy does not and should not create any data on the server, let alone the huge amount of data it creates on the p4 depot.

This is not to criticize AMD's P4 admins. They've had no choice but to enact these draconian rules to protect the stability of the service, given the aspects of Perforce that scale poorly.

**Comment by jrbriggs** [comment]
I'm closing this question, as I think it has been answered. Please let me know if you have any followups.
