### ISSUE TITLE
Mac: Write scripts\guide for capturing file system events when problems occur

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#563]
On Windows we can ask users to run [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to capture the I/O that's happening on their system when errors occur.

It sounds like `dtrace` *might* be able to get us something similar on Mac, but work needs to be done to determine how we should configure\run dtrace to get the information we're interested in.

The issue encompasses:

- Researching `dtrace` and determining what useful information can be captured and how to capture it
- Creating script(s) to start\stop `dtrace` with the options we need
- Writing up a guide on how to collect\analyze data from `dtrace`

**Comment by pmj** [comment]
After out-of-band discussion, I understand the scope of this task to be:

 * Find out what useful information we can get with dtrace.
 * Check out the extent to which this is limited by SIP, and whether we can get good enough data for most purposes while keeping SIP enabled.
 * Potentially add comprehensive tracing to any actions taken by the kext. (e.g. log every DENY kauth vnode listener response to be able to trace errors back to our kext - or not.)
 * If dtrace with SIP isn't good enough, check the feasibility of building a special purpose tracing kext.
 * Write documentation & scripts to allow end users to enable/run such diagnostic traces.

**Comment by wilbaker** [comment]
>  I understand the scope of this task to be:

@pmj that looks correct to me, thanks!

/ cc: @jrbriggs

**Comment by wilbaker** [comment]
@pmj, I think there's actually one more item to call out as being within the scope of this task:

- If the amount of useful information we can get from dtrace depends on whether SIP is enabled\disabled, write scripts that can take advantage of the extra information available when SIP is disabled.  This can be either a separate script, or as an option for a single script (that can run in both SIP modes).  This will be helpful for diagnosing issues that we can reproduce on machines where SIP is disabled.

/ cc: @jrbriggs, @nickgra

**Comment by pmj** [comment]
With #637 and #643 finally merged and with me back and refreshed(?) from my holiday break, I can now focus on this.

My initial plan was to attempt to write a DTrace script that will log any (failed?) file I/O syscalls from passed command's process and its subprocesses.

First result: SIP *very severely* restricts what we can do with DTrace. It looks like any process executing a binary with restricted entitlements is off limits. This means pretty much any binary shipped by Apple - including the entire Xcode toolchain etc. but of course also things like shell scripts because `sh`/`bash` and friends are protected too. So although e.g. Visual Studio for Mac itself isn't affected, I suspect hardly any build processes for real projects will completely avoid Apple-provided tools; and if we can't trace a process, we also can't trace its subprocesses because we don't know what processes it creates. Indeed none of the [`proc` probes](https://docs.oracle.com/cd/E37670_01/E50705/html/ol-useproc_probes.html) are available when SIP is on.

So unless we're going to ask users to [turn off at least parts of SIP](https://forums.developer.apple.com/thread/17452) we'll need to come up with something else. What would you like me to focus on?

 * Adding tracing facilities to our existing kext so we can generate a record of any kauth callback decisions made. (i.e. we can determine whether access to a specific file was blocked or not.)
 * A dtrace script that works on systems where tracing prevention has been disabled (`csrutil enable --without dtrace`)
 * Attempting to come up with a kext that hooks and logs syscalls
 * Something else?

**Comment by pmj** [comment]
The changes to `dtruss` as part of #737 should mostly get us the raw data we need. However, the output is currently a giant semi-formatted plain text file. So while it should be *possible* to track down the information, doing so by hand is cumbersome. Can we repurpose any existing tools for mining this data in a user-friendly way? If not, how far do we want to go with building our own tools, and what should the implementation look like?

**Comment by jrbriggs** [comment]
Thanks @pmj. I'm going to consider this issue closed now, and if we find that we want more data when investigating support issues we'll create other issues to track that work.
