### ISSUE TITLE
Can VFSForGit handle a ~2TB repo?

### ISSUE THREAD

**Issue by khaffner** [Microsoft/VFSForGit#659]
I'm thinking about moving a large chunk of our sccm repo into one git repo in Azure DevOps, and using VFSForGit and Git to manage the content. Some rough numbers as of today:
- 2TB total, mostly binaries
- 1-2 Million files
- Thousands of files added/changed every day
- 1Gbps internet connection
- 10 Engineers/Techs

Can I expect VFSForGit to be a working solution with those numbers? In terms of bits and bytes it's much larger than the Windows repo, but also lighter in terms of activity and branches.
What are the local bottlenecks?
So far I've only barely tested gvfs with a 700MB repo, worked great as expected.

**Comment by khaffner** [comment]
Removing the binaries from the repo would be the best solution for sure. But can this be done (via LFS or something else) in a way that still allows for the automatic pulling of required files that VFS for Git does so well?
We have no build processes in that way, we work with software installation packages for Microsoft System Center Configuration manager. Essentially a huge collection of small but critical scripts that fire up large binaries on Windows.

**Comment by jrbriggs** [comment]
I see. Yes, LFS would do that as well. The difference there is LFS would pull the files required to check out the working directory at checkout time, rather than on first access. Both VFS for Git and LFS would require the client to be properly configured. If I recall correct, Git for Windows now bundles LFS so configuration should be simple on Windows.

You could also consider [Universal Packages](https://blogs.msdn.microsoft.com/devops/2018/10/05/getting-started-with-universal-packages/) to store the binaries, and then check in a manifest declaring the necessary packages. Couple that with a small script to kick off downloading those packages and that might neatly separate those concerns.

**Comment by jrbriggs** [comment]
I'm going to close this, as I believe the question has been answered. Please let me know if you disagree.
