### ISSUE TITLE
Investigate locking on WriteAddEntry

### ISSUE THREAD

**Issue by jeschu1** [Microsoft/VFSForGit#794]
It looks like there is opportunity for duplicates in modifiedPaths because of the locking here

https://github.com/Microsoft/VFSForGit/blob/25d21da9e286eef33db635833a92cad0055923da/GVFS/GVFS.Common/ModifiedPathsDatabase.cs#L95

**Comment by kewillford** [comment]
Not sure how much this matters because the `modifiedPaths` is a hashset and will not have duplicates.  So even when this happens 
1. duplicates will not be sent to git since it is using the hashset
2. duplicates will be removed the next mount because we load from the file into the hashset and then write out all the entries that are in the hashset.

**Comment by jeschu1** [comment]
@wilbaker with that in mind, is it worth investigating more?

**Comment by jrbriggs** [comment]
I don't believe there is any further action required here. Thanks for the explanation, @kewillford.

@jeschu1 or @wilbaker please re-open if you disagree.

**Comment by wilbaker** [comment]
Yep @jrbriggs and @jeschu1 I agree with @kewillford.

@kewillford thanks for the detailed explanation!
