### ISSUE TITLE
Investigate `git push` perf issues

### ISSUE THREAD

**Issue by sanoursa** [Microsoft/VFSForGit#83]
We have heard a few reports of `git push` taking a long time to decide what to push, presumably because it is doing expensive local graph walks. Investigate further to see what we can do to optimize this.

**Comment by derrickstolee** [comment]
I just wanted to leave a few notes on this topic, since I've thought a little about this:

1. We see that force pushes are much slower than other pushes. We don't expect force-push to send more data than usual pushes on average, so this time is mostly due to a commit-graph walk that is slow. With the commit-graph feature deploying, we see this improve. We still need to do more to make the commit walk use generation numbers for even more improvements.
1. We also likely see a lot of time spent walking trees to find the set-difference between "reachable from my ref" and "known to exist on the server". This requires some more detailed measurement to know there is room to improve here.
1. Other areas that can cause slow pushes include: packing the objects into a packfile, network speed, server delay when hit with concurrent pushes. We can probably compare the client performance data with the server data to see how much is bound by network speed and server performance.

**Comment by derrickstolee** [comment]
As I was testing a new algorithm, I noticed a regular push taking a very long time. GVFS was downloading loose commits and trees! Turns out that it was a problem that my remote branches were far enough ahead of my prefetch packfiles, so it was doing a lot of round-trips to the server to compute how much data was in my local branch but not the server. Hourly prefetch packs will help this case, but it may even be worth triggering a GVFS prefetch at the start of a `git push`.

**Comment by derrickstolee** [comment]
This is resolved by an internal PR that prefetches in the background. Will also speed up most fetches.

**Comment by derrickstolee** [comment]
I'm reopening this issue, since background prefetch did not have a significant impact on push performance.

**Comment by derrickstolee** [comment]
While I'm working on some deeper changes here, I have a few "easy" fixes ready.

First one is [to use `core.warnAmbiguousRefs=false` during `pack-objects`](https://github.com/Microsoft/git/pull/67). This significantly reduces time spent looping through different file-existence checks for objects that are clearly OIDs.

**Comment by derrickstolee** [comment]
#477 adds `pack.useBitmaps = false` setting to our enlistments to avoid checking for `.bitmap` files for every pack-file.

**Comment by jrbriggs** [comment]
I'm closing this overly-broad issue now that we've put in the low-hanging fruit and taken #616 which we expect will provide substantial perf improvements. We'll open more targeted issues if we discover more bottlenecks in push.
