### ISSUE TITLE
Mac: Measure performance impact of switching to sparse-files

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#873]
We've seen reports of updating placeholders taking a long time on Mac.  This could be due to having to write out an empty file that's the same size as the file in the repo.

Experiment with sparse files on APFS and see how much of a difference this makes.

**Comment by wilbaker** [comment]
@nickgra do you remember if any performance testing of sparse-files was done when prototyping VFS4G on Mac?

**Comment by nickgra** [comment]
@wilbaker I dug up my notes from the early days and while nothing was formally done, hydrating a large set of files with the MirrorProvider before sparse-files and after went from ~7 minutes to ~2 minutes.
We ended up dropping the investigation due to concerns over having to support two code paths and that some tools that ship with Xcode didn't seem to handle sparse files correctly. 

Things have evolve a lot since then, I believe this is a good time to revisit that code change and get performance numbers.

**Comment by pmj** [comment]
D'oh, I saw the PR before this issue, so [I've already commented there](https://github.com/Microsoft/VFSForGit/pull/876#issuecomment-468908168).

HFS+ doesn't support sparse files, the closest thing to them there is to use its compression support. This amounts to writing a zlib[1]-compressed blob to a special xattr, which effectively replaces the file contents with that data. Compressing a giant blob of zero bytes should be reasonably fast, of course you could do it faster by specifically crafting the byte stream with repeated 64KiB (IIRC) all-0 DEFLATE blocks.

I'm not sure there's a difference between `ftruncate()` vs seek-and-write on APFS (Other than that seek-and-write presumably creates at least one non-sparse block at the end.), would need to check. The `du` utility isn't terribly useful for this on macOS unfortunately.

**Comment by jeschu1** [comment]
Closing, as we no longer use ftruncate to create placeholders of specific sizes
