### ISSUE TITLE
Prompts for authentication for each new repo

### ISSUE THREAD

**Issue by bk2204** [Microsoft/VFSForGit#928]
I have multiple repositories using VFSforGit stored on the same server. Each time I try to clone a new repository with `gvfs clone`, I'm prompted to log in again and must enter my username, password, and a 2FA code.

Instead, VFSforGit should prompt once to acquire a personal access token and store it in the credential manager for reuse across all repositories on that server, as upstream Git does. If the user requires different credentials for different repositories, then they can set the `credential.useHttpPath` option in their configuration to specify this, and VFSforGit can then prompt them each time.

**Comment by jamill** [comment]
Hi!

Great feedback. We effectively force `credential.useHttpPath` for all of our VFS4G repositories currently, as some remotes require it to authenticate as expected - in particular internal repositories that we support. This is unnecessary (and has negative consequences) in general.

I think one option is for our team to handle setting the `useHttpPath` as an internal concern (e.g. in our internal setup) rather than pushing this behavior into the general behavior for VFSForGit.

**Comment by jamill** [comment]
Addressed with #939
